### ISSUE TITLE
codechef_sol

### ISSUE THREAD

**Issue by RAJEEVKUMAR9598** [bishweashwarsukla/hactoberfest2022#63]
HII @bishweashwarsukla CAN I SHARE SOME CODECHEF LONG CHALLENGE SOLUTION..

**Comment by RAJEEVKUMAR9598** [comment]
PLEASE ASSIGN ME THIS TASK

**Comment by bishweashwarsukla** [comment]
Ya you can add those files. Just send a PR. No need to particularly assigning to you.
